notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"

language: python
python:
  - "2.7"

addons:
  apt:
    packages:
    - glpk-utils

install:
  - pip install -r requirements.txt
  - pip install flake8
  - python setup.py install

script:
  - py.test tests -v
  - flake8 .
